urls.py
from django.conf.urls.defaults import *
from django.views.generic import ListView
from django.views.generic.base import RedirectView
from staff.models import Staffer
from staff.views import StaffListView, PrivateStaffListView

urlpatterns = patterns('',
    (r'^phone-list/$', PrivateStaffListView.as_view(
        queryset = Staffer.objects.filter(active=True).exclude(extension='').order_by('last_name'),
    )),
    (r'^internal/$', ListView.as_view(
        queryset = Staffer.objects.filter(active=True).order_by('last_name'),
    )),
    (r'^$', RedirectView.as_view(url='http://www.registerguard.com/contact', permanent=True)),
)

models.py
from os import path
from django.core import exceptions
from django.db import models
from sorl.thumbnail import get_thumbnail, ImageField

class TopSection(models.Model):
    top_section_group = models.CharField(max_length=150)
    extra_text = models.CharField(max_length=128, blank=True)
    slug = models.SlugField(max_length=120, unique=True, blank=True)
    
    class Meta:
        ordering = ['top_section_group']
    
    def __unicode__(self):
        return u'%s' % (self.top_section_group)

class Department(models.Model):
    '''
    See https://github.com/praekelt/django-category/blob/master/category/models.py
    '''
    department_title = models.CharField(max_length=128)
    slug = models.SlugField(max_length=120, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='child')
    
    class Meta:
        ordering = ['department_title']
    
    def __unicode__(self):
        p_list = self._recurse_for_parents(self)
        p_list.append(self.department_title)
        return self.get_separator().join(p_list)
    
    def _recurse_for_parents(self, cat_obj):
        p_list = []
        if cat_obj.parent_id:
            p = cat_obj.parent
            p_list.append(p.department_title)
            more = self._recurse_for_parents(p)
            p_list.extend(more)
        if cat_obj == self and p_list:
            p_list.reverse()
        return p_list
    
    def get_separator(self):
        return ' :: '
    
    def _parents_repr(self):
        p_list = self._recurse_for_parents(self)
        return self.get_separator().join(p_list)
    _parents_repr.short_description = 'Department parents'
    
    def save(self):
        p_list = self._recurse_for_parents(self)
        if self.department_title in p_list:
            raise exceptions.ValidationError('You must not save a category in itself')
        super(Department, self).save()

class Staffer(models.Model):
    def staff_photo_file_name(instance, filename):
        (orig_name, orig_ext) = path.splitext(filename)
        return 'uploads/staff/staff.%s.%s%s' % (instance.first_name_middle.lower(), instance.last_name.lower(), orig_ext)
    
    old_id = models.IntegerField(blank=True, null=True)
    old_site_id = models.IntegerField(blank=True, null=True)
    old_weblog_id = models.IntegerField(blank=True, null=True)
    cgi_id = models.IntegerField(blank=True, null=True)
    cgi_photo_id = models.IntegerField(blank=True, null=True)
    supra = models.BooleanField(blank=True, help_text=u'Use this check box if this staffer is to be listed at the top of the staff page.', verbose_name=u'In a top group?')
    supra_order = models.IntegerField(blank=True, null=True, help_text=u'Order of name within group at top of staff page. i.e, No. 5 in \'General news coverage\' section.', verbose_name=u'Order within group')
    twitter_id = models.CharField(u'Twitter handle', max_length=100, blank=True, help_text=u'Without the "@" sign.')
    photo = ImageField(upload_to=staff_photo_file_name, blank=True)
    first_name_middle = models.CharField(max_length=256, blank=True)
    last_name = models.CharField(max_length=256, blank=True)
    position = models.CharField(max_length=128, blank=True)
    bio = models.TextField(blank=True)
    contact_info = models.TextField(max_length=256, blank=True)
    address = models.TextField(max_length=300, blank=True)
    email = models.EmailField(blank=True)
    other_email = models.EmailField(blank=True)
    phone = models.CharField(max_length=26, blank=True)
    extension = models.CharField(max_length=26, blank=True)
    cell_phone = models.CharField(max_length=26, blank=True)
    home_phone = models.CharField(max_length=26, blank=True)
    more_info = models.CharField(max_length=256, blank=True)
    active = models.BooleanField(default=True)
    hire_date = models.DateField(null=True, blank=True)
    birth_date = models.DateField(blank=True, null=True)
    mystery_date_time = models.DateTimeField(blank=True, null=True, help_text=u'This datetime came from the data from the old cgi-bin system. Don\'t know what it means, but it was brought over.')
    last_modified = models.DateTimeField(auto_now=True)
    department = models.ForeignKey(Department, null=True)
    top_section = models.ForeignKey(TopSection, blank=True, null=True, verbose_name=u'Top section group name')
    
    def __unicode__(self):
        return u'%s %s' % (self.first_name_middle, self.last_name)
    
    def admin_thumbnail(self):
        if self.photo:
            im = get_thumbnail(self.photo, '60')
            return u'<a href="http://%s.%s/%s"><img src="%s" width="60" alt="%s %s" /></a>' % (self.photo.storage.bucket, self.photo.storage.connection.server, self.photo.name, im.url, self.first_name_middle, self.last_name)
        else:
            return u'(No photo)'
    admin_thumbnail.short_description = u'Thumbnail'
    admin_thumbnail.allow_tags = True
    
    def full_name(self):
        return u'%s %s' % (self.first_name_middle, self.last_name)

views.py
from django.contrib.sites.models import Site
from django.db.models import Q
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from staff.models import Staffer, Department

# Create your views here.

'''
TO DO:
Remove unnecessary model fields.
Re-order legacy id fields.

DONE:
Created IP-checking view/decorator.
64.112.229.222
http://stackoverflow.com/questions/12383540/authenticate-by-ip-address-in-django
https://docs.djangoproject.com/en/1.5/topics/class-based-views/intro/#s-decorating-the-class
https://github.com/registerguard/tracker/issues/489
'''

AUTHORIZED_IPS = ['64.112.229.222',]

def ip_authorization(view_func):
    def authorize(request, *args, **kwargs):
        request_ip = request.META['REMOTE_ADDR']
        if request_ip in AUTHORIZED_IPS or request.user.is_authenticated():
            return view_func(request, *args, **kwargs)
        else:
            return HttpResponse(status=401)
    return authorize

class StaffListView(ListView):
    
    template_name = 'staff/staff_list.html'
    
    def get_queryset(self):
         # return Staffer.objects.filter(active=True).exclude(extension='').exclude(department__department_title='Production').order_by('department', 'last_name')
         return Staffer.objects.filter(active=True).exclude(department__department_title='Production').order_by('department', 'last_name')
    
    def get_context_data(self, **kwargs):
        context = super(StaffListView, self).get_context_data(**kwargs)
        context.update({
            'current_site': Site.objects.get_current(),
            'departments': Department.objects.exclude(department_title='Production'),
            'last_modified': Staffer.objects.all().order_by('-last_modified')[:1],
            'selecteds': Staffer.objects.filter(supra=True, active=True).order_by('top_section__top_section_group', 'supra_order'),
            'page': {'title': 'Contact us', 'description_short': 'staff directory'},
        })
        return context

class PrivateStaffListView(ListView):
    @method_decorator(ip_authorization)
    def dispatch(self, *args, **kwargs):
        return super(PrivateStaffListView, self).dispatch(*args, **kwargs)

    template_name = 'staff/staff_list_internal.html'

    def get_queryset(self):
        return Staffer.objects.filter(Q(active=True, department__department_title='News') | Q(last_name='Lyon')).order_by('last_name')

templates/staff/staff_list.html
{% extends "dox/bulldog.html" %}

{% load encode_mailto %}

{% block head_title %}Contact us{% endblock head_title %}

{% block head_description %}Contact The Register-Guard by department or name.{% endblock head_description %}

{% block head_keywords %}registerguard,contact,staff,department,name{% endblock head_keywords %}

{% block content %}
	
	<div class="give take">
		
		<section>
			
			<h1 class="reverse">Departments</h1>
			
			<ul class="li1">
				
				{% for department in departments %}
					<li><a href="#{{ department.department_title|lower }}">{{ department.department_title }}</a></li>
				{% endfor %}
				
			</ul> <!-- /.li1 -->
			
			<h2 class="reverse">Feedback</h2>
			
			<h3 class="h4">Have a suggestion, comment, complaint?</h3>
			<p>We welcome comments from readers. If you have general suggestions, please contact the following:</p>
			
			{% regroup selecteds by top_section as selecteds_list %}
			
			<ul class="li2">
			
				{% for selected_name in selecteds_list %}
					
					<li>
						
						<b>{{ selected_name.grouper|safe }}</b>
						
						{% if selected_name.grouper.extra_text %}
							<br>
							<i>{{ selected_name.grouper.extra_text|safe }}</i>
						{% endif %}
						
						<ul>
							
							{% for selected in selected_name.list %}
								
								<li>{{ selected.position }}: {{ selected.email|encode_mailto:selected.full_name|safe }}</li>
								
							{% endfor %}
							
						</ul>
						
					</li>
					
				{% endfor %}
				
			</ul> <!-- /.li2 -->
			
			<h2 class="reverse">Department directory</h2>
			
			{% regroup object_list by department as staffer_list %}
			
			<ul class="li2">
			
				{% for staffer in staffer_list %}
					
					<li id="{{ staffer.grouper|lower }}">
						
						<b>{{ staffer.grouper }}</b>
						
						<ul>
							
							{% for employee in staffer.list %}
								
								<li>
									{{ employee.first_name_middle }} {{ employee.last_name }}{% if employee.position %}, {{ employee.position }}{% endif %}{% if employee.more_info %}, <i>{{ employee.more_info }}</i>{% endif %}{% if employee.email %}, {{ employee.email|encode_mailto:employee.email|safe }}{% endif %}{% if employee.other_email %}, {{ employee.other_email|encode_mailto:employee.other_email|safe }}{% endif %}{% if employee.extension %}, 541-338-{{ employee.extension }}{% else %}, {{ employee.phone }}{% endif %}
									{% if employee.twitter_id %}
										<br>
										<a href="https://twitter.com/{{ employee.twitter_id }}" class="twitter-follow-button" data-show-count="true">Follow {{ employee.twitter_id }}</a>
									{% endif %}
								</li>
							{% endfor %}
							
						</ul>
						
					</li>
					
				{% endfor %}
				
			</ul> <!-- /.li2 -->
			
			<small>Last modified: {{ last_modified.0.last_modified }}</small>
			
		</section>
		
	</div> <!-- /.give -->
	
{% endblock content %}

{% block footer_extra %}
	
	{{ block.super }}
	
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
	
{% endblock footer_extra %}

templates/staff/staff_list_internal.html
<!DOCTYPE html>
<html lang=en>
<head>
<meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1">
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>
<style>
.table-condensed>tbody>tr>td, .table-condensed>tbody>tr>th, 
.table-condensed>tfoot>tr>td, .table-condensed>tfoot>tr>th, 
.table-condensed>thead>tr>td, .table-condensed>thead>tr>th {
	padding: 1px;
}
</style>
</head>
<body>
	<div class="container">
		<h2>Newsroom phone list</h2>
		<p>This page is only reachable from within the building or if you're authenticated (logged in) outside of it. {#Corrections to <a href="mailto:webeditors@registerguard.com?subject=Phone list correction">webeditors@registerguard.com</a>. #}(See John, Rob or Carl if you don't have a log in.)</p>
		<div class="table-responsive">
			<table class="table table-condensed table-striped">
				<thead>
				<tr>
					<th>Name</th>
					<th>Extension</th>
					<th>Cell</th>
					<th>Home</th>
					<th>Address</th>
				</tr>
				</thead>
				<tbody>
				{% for staffer in object_list %}
				<tr>
					<td>{{ staffer.last_name }}, {{ staffer.first_name_middle }}</td>
					<td>{{ staffer.extension }}</td>
					<td>{{ staffer.cell_phone }}</td>
					<td>{{ staffer.home_phone }}</td>
					<td>{{ staffer.address }}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</body>
</html>

templates/staff/staffer_list.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<title>Staff phone list</title>
		
		<style type="text/css">
			div#multicolumn1 {
				-moz-column-count: 4;
				-moz-column-gap: 10px;
				-webkit-column-count: 4;
				-webkit-column-gap: 10px;
				column-count: 4;
				column-gap: 10px;
				width: 750px;
			}
			
			.ext {
				float: right;
				background: none repeat scroll #FFFFFF;
			}
			
			ul {
				margin: 0 0 0 0;
				padding-left: 0;
			}
			
			li {
				background: url("http://assets.registerguard.com/v4.0/services/1.0/css/../images/template/rule-01.gif") repeat-x scroll left bottom transparent;
				list-style: none outside none;
				font: 13px/1.231 arial,helvetica,clean,sans-serif;
			}
			
			li a {
				background: none repeat scroll #FFFFFF;
				text-decoration: none;
			}
			.tip {
				color: #fff;
				background:#1d1d1d;
				display:none; /*--Hides by default--*/
				padding:10px;
				position:absolute;    z-index:1000;
				-webkit-border-radius: 3px;
				-moz-border-radius: 3px;
				border-radius: 3px;
			}
		</style>
	</head>
	<body>
		<div id="multicolumn1">
			<ul>
			{% for staffer in object_list %}
				<li><a href="#" class="tip_trigger">{{ staffer.last_name }}, {{ staffer.first_name_middle }}<span class="tip"><img src='http://intranet2.guardnet.com/photoid/{{ staffer.cgi_photo_id }}.jpg'></span></a> <span class="ext">{{ staffer.extension }}</span></li>
			{% endfor %}
			</ul>
		</div>
	<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				//Tooltips
				$(".tip_trigger").hover(function(){
					tip = $(this).find('.tip');
					tip.show(); //Show tooltip
				}, function() {
					tip.hide(); //Hide tooltip
				}).mousemove(function(e) {
					var mousex = e.pageX + 20; //Get X coodrinates
					var mousey = e.pageY + 20; //Get Y coordinates
					var tipWidth = tip.width(); //Find width of tooltip
					var tipHeight = tip.height(); //Find height of tooltip
			
					//Distance of element from the right edge of viewport
					var tipVisX = $(window).width() - (mousex + tipWidth);
					//Distance of element from the bottom of viewport
					var tipVisY = $(window).height() - (mousey + tipHeight);
			
					if ( tipVisX < 20 ) { //If tooltip exceeds the X coordinate of viewport
						mousex = e.pageX - tipWidth - 20;
					} if ( tipVisY < 20 ) { //If tooltip exceeds the Y coordinate of viewport
						mousey = e.pageY - tipHeight - 20;
					}
					//Absolute position the tooltip according to mouse position
					tip.css({  top: mousey, left: mousex });
				});
			});
		</script>
	</body>
</html>